### PR TITLE
Allows people to start w/o scrolling

### PR DESCRIPTION
**Pull request by adriancole**
I noticed the README is long and think maybe this helps? WDYT?

Idea is you have the command there when you lose interest in scrolling down.

### CODE REVIEW

**Review by jorgheymans — APPROVED** [review]
:+1:

**Comment by jcchavezs** [comment]
This image tagging with the example name is too much. I really can't imagine where it is the limit when it comes to make things easier for users.

**Comment by adriancole** [comment]
> This image tagging with the example name is too much. I really can't imagine where it is the limit when it comes to make things easier for users.

I have another thought to improve, which is to use table layout to put the instrumentation details only on one line below the command used to *go!*

will try it later. thanks for the feedback

**Comment by adriancole** [comment]
follow up https://github.com/openzipkin/brave-example/pull/53/files?short_path=b335630#diff-04c6e90faac2675aa89e2176d2eec7d8

**Pull request merged**
