### PR TITLE
armeria: showcase Eureka integration 

### PR DESCRIPTION
**Pull request by codefromthecrypt**
Note: If you don't set zipkin's `EUREKA_HOSTNAME=zipkin` then clients will crash hard like this. It may be something to fix in armeria, or maybe we should require explicit setting. 

```bash
$ build-bin/docker/docker_build openzipkin/brave-example:armeria-test
--snip--
$  docker-compose -f docker-compose.yml -f docker-compose-eureka.yml up
--snip--
backend   | 08:01:00.115 [armeria-common-worker-epoll-2-2] [] [/] WARN  c.l.a.c.eureka.EurekaEndpointGroup - Unexpected exception while parsing a response from: http://eureka:8761/eureka/v2. (content: {"application":{"name":"ZIPKIN","instance":[{"instanceId":"08d1cd941327:zipkin:9411","hostName":"08d1cd941327","app":"ZIPKIN","ipAddr":"172.21.0.3","status":"UP","overriddenStatus":"UNKNOWN","port":{"$":9411,"@enabled":"true"},"securePort":{"$":0,"@enabled":"false"},"countryId":1,"dataCenterInfo":{"@class":"com.netflix.appinfo.InstanceInfo$DefaultDataCenterInfo","name":"MyOwn"},"leaseInfo":{"renewalIntervalInSecs":30,"durationInSecs":90,"registrationTimestamp":1705219255654,"lastRenewalTimestamp":1705219255654,"evictionTimestamp":0,"serviceUpTimestamp":1705219255086},"metadata":{"@class":"java.util.Collections$EmptyMap"},"healthCheckUrl":"http://172.21.0.3:9411/health","vipAddress":"08d1cd941327:9411","isCoordinatingDiscoveryServer":"false","lastUpdatedTimestamp":"1705219255654","lastDirtyTimestamp":"1705219254880","actionType":"ADDED"}]}}, responseConverter: com.linecorp.armeria.client.eureka.EurekaEndpointGroup$ApplicationConverter@7d7d125f, requestHeaders: [:method=GET, :path=/apps/zipkin, accept=application/json; charset=utf-8])
backend   | java.lang.IllegalArgumentException: Not a valid domain name: '08d1cd941327'
backend   | 	at com.linecorp.armeria.internal.shaded.guava.base.Preconditions.checkArgument(Preconditions.java:218)
backend   | 	at com.linecorp.armeria.internal.shaded.guava.net.InternetDomainName.<init>(InternetDomainName.java:162)
backend   | 	at com.linecorp.armeria.internal.shaded.guava.net.InternetDomainName.from(InternetDomainName.java:252)
backend   | 	at com.linecorp.armeria.client.Endpoint.normalizeHost(Endpoint.java:222)
backend   | 	at com.linecorp.armeria.client.Endpoint.create(Endpoint.java:207)
backend   | 	at com.linecorp.armeria.client.Endpoint.of(Endpoint.java:133)
backend   | 	at com.linecorp.armeria.client.eureka.EurekaEndpointGroup.endpoint(EurekaEndpointGroup.java:412)
backend   | 	at com.linecorp.armeria.client.eureka.EurekaEndpointGroup.lambda$endpoints$8(EurekaEndpointGroup.java:362)
```

### CODE REVIEW

**Comment by codefromthecrypt** [comment]
here is how we currently register zipkin https://github.com/openzipkin/zipkin/blob/master/zipkin-server/src/main/java/zipkin2/server/internal/eureka/ZipkinEurekaDiscoveryProperties.java#L74-L80

We don't set a default value for the zipkin hostname, so it is detecting it.. I guess in an incorrect way? https://github.com/openzipkin/zipkin/blob/master/zipkin-server/src/main/resources/zipkin-server-shared.yml#L73

**Comment by codefromthecrypt** [comment]
maybe we can't detect the correct hostname in docker and should always set it..

**Comment by codefromthecrypt** [comment]
I'm not sure if armeria could discover the correct hostname to use for eureka discovery or not. For now, I'll just change the examples to specify it explicitly.

**Comment by codefromthecrypt** [comment]
ok done on a released version

**Review by anuraaga — APPROVED** [review]

**Pull request merged**
