### PR TITLE
Publishes to GitHub Container Registry instead of Docker Hub

### PR DESCRIPTION
**Pull request by adriancole**
As mentioned in https://github.com/openzipkin/docker-java/pull/33, we
are no longer pushing images to Docker Hub that are used in CI loops.

This prevents us and others from hitting the 100 or 200 Docker pull
limits applying on November 1st. While Zipkin images will continue to
push to DockerHub example images like these won't.

This implies changing your files like below:
```diff
-    image: openzipkin/example-brave:${PROJECT:-armeria}
+    image: ghcr.io/openzipkin/brave-example:${PROJECT:-armeria}
```

It not may seem intuitive to use Travis to push the images, but it is
quicker for me, and easy enough for someone else to refactor into a
GitHub action later. There are only a few more days before the new
limits apply and I have a lot of other work to do including unrelated
to Zipkin.

### CODE REVIEW

**Comment by adriancole** [comment]
here is the package published on merge.. I executed the same script that would run on master (it is still running :P ) https://github.com/orgs/openzipkin/packages/container/package/brave-example

The pull request checker doesn't push anything, it does what it did before, which is pull and build. Since the images pulled are from ghcr.io we shouldn't expect any limits to hit, even if someone makes 200 revs to one pull request.

**Comment by adriancole** [comment]
Here are some screen shots from the pull request checker, showing it is not hitting dockerhub anymore

Screen Shot 2020-10-27 at 1 17 42 PM
Screen Shot 2020-10-27 at 1 17 54 PM

**Comment by adriancole** [comment]
eek except maybe scratch... @anuraaga is scratch a real image? I think it isn't right?

**Comment by adriancole** [comment]
ok on scratch:

> As of Docker 1.5.0 (specifically, docker/docker#8827), FROM scratch is a no-op in the Dockerfile, and will not create an extra layer in your image (so a previously 2-layer image will be a 1-layer image instead).
https://hub.docker.com/_/scratch/

**Review by anuraaga — APPROVED** [review]
Learned that scratch isn't a layer, sweet

**Comment by adriancole** [comment]
I will watch and report back either way if travis publishes the image or not.

**Pull request merged**
