### PR TITLE
Updates to Brave 6

### PR DESCRIPTION
**Pull request by codefromthecrypt**

### CODE REVIEW

**Comment by codefromthecrypt** [comment]
@anuraaga @reta I'm going to hold off Brave 6 until I get to the bottom of this.. I think maybe the issue is in zipkin-reporter repo, because the AsyncZipkinSpanHandler extends ZipkinSpanHandler which references the types. I'll see if I need to unhook them.

```
 backend         | Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'tracing' defined in class path resource [brave/example/TracingAutoConfiguration.class]: Unsatisfied dependency expressed through method 'tracing' parameter 5; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'zipkinSpanHandler' defined in class path resource [brave/example/TracingAutoConfiguration.class]: Initialization of bean failed; nested exception is java.lang.TypeNotPresentException: Type zipkin2.Span not present
```

**Comment by codefromthecrypt** [comment]
found the issue with spring https://github.com/openzipkin/zipkin-reporter-java/pull/238 once merged, I'll try here with snapshot repo to verify in a way besides my laptop

**Comment by codefromthecrypt** [comment]
looking good! the kafka one is legit as the api used was deprecated in brave! cc @jeqo @reta!

**Comment by codefromthecrypt** [comment]
ok all green now.. brave is ready to ship!

**Review by reta — APPROVED** [review]

**Pull request merged**
